import { useState } from "react";
import { Node, Edge } from "reactflow";
import {
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Button } from "./ui/button";
import { ScrollArea } from "./ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { generateDaoContracts as generatePlaceholderContracts } from "@/lib/contract-generator";
import { generateFinalContractsFromAI } from "@/lib/gemini";
import { uploadJsonToIpfs } from "@/lib/ipfs";
import { showSuccess, showError, showLoading, dismissToast } from "@/utils/toast";
import { Bot, FileCode, Loader, AlertTriangle, UploadCloud, PenSquare, Rocket, CheckCircle } from "lucide-react";
import { useAccount, useWriteContract, useWalletClient, usePublicClient } from "wagmi";
import { daoRegistryAddress, daoRegistryAbi } from "@/lib/contracts";
import { deployDAO } from "@/lib/deployment-manager";

interface DeploymentPanelProps {
  nodes: Node[];
  edges: Edge[];
}

type DeploymentStep = 'idle' | 'generating' | 'generated' | 'deploying' | 'deployed' | 'uploading' | 'uploaded' | 'registering' | 'registered';

export const DeploymentPanel = ({ nodes, edges }: DeploymentPanelProps) => {
  const [contracts, setContracts] = useState<{ filename: string, code: string }[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [ipfsCid, setIpfsCid] = useState<string | null>(null);
  const [daoAddress, setDaoAddress] = useState('');
  const [deploymentStatus, setDeploymentStatus] = useState<string[]>([]);
  const [step, setStep] = useState<DeploymentStep>('idle');

  const { isConnected } = useAccount();
  const { data: walletClient } = useWalletClient();
  const publicClient = usePublicClient();
  const { writeContract, isPending: isRegistering, data: hash } = useWriteContract();

  const handleGenerateContracts = async () => {
    setStep('generating');
    setError(null);
    setContracts([]);
    setIpfsCid(null);

    try {
      const placeholders = generatePlaceholderContracts(nodes, edges);
      if (placeholders.length === 0) {
        throw new Error("No contracts could be generated. Please add and connect nodes on the canvas.");
      }
      const finalContracts = await generateFinalContractsFromAI(nodes, edges, placeholders);
      setContracts(finalContracts);
      setStep('generated');
    } catch (e) {
      const errorMessage = e instanceof Error ? e.message : "An unknown error occurred.";
      setError(errorMessage);
      setStep('idle');
    }
  };

  const handleDeploy = async () => {
    if (!walletClient || !publicClient) {
      showError("Wallet not connected or configured properly.");
      return;
    }
    if (contracts.length === 0) {
      showError("Please generate contracts before deploying.");
      return;
    }

    setStep('deploying');
    setDeploymentStatus([]);
    setError(null);
    const toastId = showLoading("Starting DAO deployment...");

    const updateStatus = (message: string) => {
      setDeploymentStatus(prev => [...prev, message]);
    };

    try {
      const { daoAddress: deployedDaoAddress } = await deployDAO(
        nodes,
        edges,
        contracts,
        walletClient,
        publicClient,
        updateStatus
      );
      
      setDaoAddress(deployedDaoAddress);
      dismissToast(toastId);
      showSuccess("DAO deployed successfully!");
      setStep('deployed');

    } catch (e) {
      const errorMessage = e instanceof Error ? e.message : "An unknown error occurred during deployment.";
      dismissToast(toastId);
      showError(errorMessage);
      setError(errorMessage);
      setStep('generated'); // Revert to previous step on failure
    }
  };

  const handleUploadAndRegister = async () => {
    if (!daoAddress.startsWith('0x') || daoAddress.length !== 42) {
      showError("A valid deployed DAO address is required.");
      return;
    }
    if (!isConnected) {
      showError("Please connect your wallet.");
      return;
    }

    // Upload to IPFS
    setStep('uploading');
    const uploadToastId = showLoading("Uploading DAO info to IPFS...");
    let cid;
    try {
      const metadata = {
        name: "AI Generated DAO",
        description: "DAO configuration generated by AI DAO Creator",
        daoAddress,
        nodes,
        edges,
        contracts,
      };
      cid = await uploadJsonToIpfs(metadata);
      setIpfsCid(cid);
      dismissToast(uploadToastId);
      showSuccess("DAO info uploaded to IPFS!");
      setStep('uploaded');
    } catch (e) {
      const errorMessage = e instanceof Error ? e.message : "IPFS upload failed.";
      dismissToast(uploadToastId);
      showError(errorMessage);
      setStep('deployed'); // Revert
      return;
    }

    // Register on-chain
    setStep('registering');
    writeContract({
      address: daoRegistryAddress,
      abi: daoRegistryAbi,
      functionName: 'registerDAO',
      args: [daoAddress as `0x${string}`, cid],
    }, {
      onSuccess: (txHash) => {
        showSuccess(`DAO registration submitted!`);
        setStep('registered');
        console.log("Transaction Hash:", txHash);
      },
      onError: (error) => {
        showError(error.shortMessage || "Registration failed.");
        setStep('uploaded'); // Revert
      }
    });
  };

  const renderContractPreview = () => {
    if (step === 'generating') {
      return (
        <div className="flex-1 flex flex-col justify-center items-center text-center p-8 border rounded-lg bg-muted">
          <Loader className="h-12 w-12 mb-4 text-primary animate-spin" />
          <p className="text-sm text-muted-foreground">AI is writing your smart contracts...</p>
        </div>
      );
    }

    if (contracts.length === 0) {
      return (
        <div className="flex-1 flex flex-col justify-center items-center text-center p-8 border rounded-lg bg-muted">
          <Bot className="h-12 w-12 mb-4 text-muted-foreground" />
          <p className="text-sm text-muted-foreground">Your generated smart contracts will appear here.</p>
        </div>
      );
    }

    return (
      <div className="flex-1 flex flex-col overflow-hidden border rounded-lg">
        <Tabs defaultValue={contracts[0].filename} className="h-full flex flex-col">
          <TabsList className="m-2">
            {contracts.map(contract => (
              <TabsTrigger key={contract.filename} value={contract.filename}>{contract.filename}</TabsTrigger>
            ))}
          </TabsList>
          {contracts.map(contract => (
            <TabsContent key={contract.filename} value={contract.filename} className="flex-1 overflow-hidden">
              <ScrollArea className="h-full">
                <pre className="text-xs bg-background p-4"><code>{contract.code}</code></pre>
              </ScrollArea>
            </TabsContent>
          ))}
        </Tabs>
      </div>
    );
  };

  return (
    <SheetContent className="w-[600px] sm:w-[740px] flex flex-col">
      <SheetHeader>
        <SheetTitle>Deploy Your DAO</SheetTitle>
        <SheetDescription>
          A step-by-step guide to generating, deploying, and registering your DAO on-chain.
        </SheetDescription>
      </SheetHeader>
      
      <div className="flex-1 flex flex-col py-4 space-y-4 overflow-hidden">
        {/* Step 1: Generation */}
        <Button onClick={handleGenerateContracts} disabled={step !== 'idle' && step !== 'generated'}>
          {step === 'generating' ? <Loader className="mr-2 h-4 w-4 animate-spin" /> : <FileCode className="mr-2 h-4 w-4" />}
          Step 1: Generate & Preview Contracts
        </Button>

        {renderContractPreview()}

        {error && (
          <div className="text-center p-4 rounded-lg bg-destructive/10 border border-destructive/50">
            <p className="text-sm font-semibold text-destructive">An Error Occurred</p>
            <p className="text-xs text-destructive/80 mt-1">{error}</p>
          </div>
        )}

        {/* Step 2: Deployment */}
        {step === 'generated' && (
          <Button onClick={handleDeploy} disabled={!isConnected}>
            <Rocket className="mr-2 h-4 w-4" />
            Step 2: Deploy Contracts
          </Button>
        )}

        {step === 'deploying' && (
          <div className="p-4 border rounded-lg bg-muted/40 flex-1 overflow-y-auto">
            <h3 className="font-semibold mb-2 flex items-center"><Loader className="mr-2 h-4 w-4 animate-spin" /> Deployment in Progress...</h3>
            <ul className="text-xs space-y-1 list-inside">
              {deploymentStatus.map((status, index) => <li key={index} className="break-all">{status}</li>)}
            </ul>
          </div>
        )}

        {/* Step 3: Registration */}
        {(step === 'deployed' || step === 'uploading' || step === 'uploaded' || step === 'registering' || step === 'registered') && (
          <>
            <div className="p-4 border rounded-lg bg-green-500/10 text-green-700 flex items-center gap-3">
              <CheckCircle className="h-5 w-5" />
              <div>
                <h3 className="font-semibold">Deployment Successful!</h3>
                <p className="text-xs break-all">DAO Address: {daoAddress}</p>
              </div>
            </div>
            <Button onClick={handleUploadAndRegister} disabled={step === 'uploading' || step === 'registering' || step === 'registered'}>
              {(step === 'uploading' || step === 'registering') && <Loader className="mr-2 h-4 w-4 animate-spin" />}
              {step === 'registered' ? <CheckCircle className="mr-2 h-4 w-4" /> : <PenSquare className="mr-2 h-4 w-4" />}
              Step 3: Upload & Register On-Chain
            </Button>
            {hash && (
              <div className="text-center">
                <p className="text-xs text-muted-foreground">
                  Registration transaction sent! <a href={`https://sepolia.etherscan.io/tx/${hash}`} target="_blank" rel="noopener noreferrer" className="underline">View on Etherscan</a>
                </p>
              </div>
            )}
          </>
        )}
      </div>
    </SheetContent>
  );
};